### ISSUE TITLE
ledger emacs doesn't escape double quotes (BZ#396)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1468]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#396
From: Lukasz Stelmach (@stelmi)

**Comment by nonducor** [comment]
I found that this issue is not solved. In ledger version "next", the emacs command doesn't escape double quotes when they appear on the "payee" field. I have attached a test case: [example.txt](https://github.com/ledger/ledger/files/2059856/example.txt)

The solution is pretty simple (I tested it on my machine and it works): [quotes.patch.txt](https://github.com/ledger/ledger/files/2059873/quotes.patch.txt)

**Comment by kcwu** [comment]
I found this issue, too. @nonducor  Please send PR or open a new issue.
