### ISSUE TITLE
0.005 rounded down instead of up

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1663]
3 * 1.595 = 4.785 which should imho be rounded up to 4.79 but ledger seems to round it down to 4.78.  I'm surprised because I'm sure someone else would have noted that already.
```
ledger -f rounding.ledger bal cash
           -4.78 EUR  Assets:Cash
```
Test case:
```
D 1000.00 EUR

; 3 * 1.595 is 4.785 which should imho be rounded to 4.79 but
; ledger shows 4.78.

2018-01-02 * Bought FOO
    Assets:Investments           3 FOO @ 1.595 EUR
    Assets:Cash
```

**Comment by tbm** [comment]
I spoke to John about this yesterday:

```
20:34 < tbm> hey johnw is it expected that 0.955 gets rounded to 0.95 instead of 0.96?
22:03 < johnw> tbm: let me check
22:04 < johnw> tbm: https://github.com/ledger/ledger/blob/next/src/amount.cc#L685
22:04 < johnw> we use ceil(), so I would have thought it would be 0.96
22:05 < johnw> but maybe that's only for roundto
22:05 < tbm> yeah, 0.96 seems correct to me but that's not what I got
22:06 < johnw> oh, it's this:
22:06 < johnw> mpfr_asprintf(&buf, "%.*RNf", precision, tempfb)
22:06 < johnw> https://github.com/ledger/ledger/blob/next/src/amount.cc#L144
22:06 < johnw> according to MPFR docs: 'N' round to nearest
22:06 < johnw> so yeah, we round toward 0
22:07 < johnw> or rather, in this case we should round away from 0....
22:07 < johnw> hmm
22:07 < johnw> maybe some debug code in stream_out_mpq would clarify this
22:07 < johnw> we also use GMP_RNDN, which should also mean nearest
22:07 < johnw> I wonder if something gets lost in the math that we do there
22:10 < johnw> you can set --debug=amount.convert
22:11 < tbm> Ok, I'll try that another day
22:15 < johnw> but please open a bug on this
22:15 < johnw> we shouldn't lose this test case that you have
22:16 < tbm> yeah, will do tomorrow
```

**Comment by tbm** [comment]
With `--debug=amount.convert`:

```
   14ms  [DEBUG] Rational to convert = -957/200
   14ms  [DEBUG] num prec = 394
   15ms  [DEBUG] den prec = 392
   15ms  [DEBUG] mpfr_print = -4.78 (precision 2, zeros_prec -1)
```

**Comment by jwiegley** [comment]
`roundto` gives the behavior you expected:

```
ledger eval 'roundto(3 * 1.595, 2)'
>>> 4.79
```

So it's the logic inside `stream_out_mpq`, which does the rounding by way of `mpfr_printf`, that seems to need adjustment.

**Comment by tbm** [comment]
@q3aiml Andy can you look at this issue?

**Comment by q3aiml** [comment]
I think this is what round to nearest means for mpfr. Rounding away from zero is a different mode.

From https://www.mpfr.org/mpfr-current/mpfr.html:

> The ‘round to nearest’ mode works as in the IEEE 754 standard: in case the number to be rounded lies exactly in the middle of two representable numbers, it is rounded to the one with the least significant bit set to zero. For example, the number 2.5, which is represented by (10.1) in binary, is rounded to (10.0)=2 with a precision of two bits, and not to (11.0)=3. This rule avoids the drift phenomenon mentioned by Knuth in volume 2 of The Art of Computer Programming (Section 4.2.2).

Do most people believe round to zero is better in this case? I haven't considered it enough to have an opinion yet.

**Comment by tbm** [comment]
Adding @simonmichael 

round to zero sounds wrong.

We need something that rounds:

* 0.015 to 0.02
* 0.0149 to 0.01

That is imho the accepted rounding practice when it comes to money.

Hmm ok, I guess in reality it might be slightly more complicated because banks sometimes round down. Maybe there has to be support for specifying rounding on a case-by-case basis.

But I think what I describe above is the most sensible default.

In Python, I can do it like this:

```
>>> import decimal
>>> decimal.Decimal('0.015').quantize(D('.01'), rounding=decimal.ROUND_HALF_UP)
Decimal('0.02')
>>> decimal.Decimal('0.014999').quantize(D('.01'), rounding=decimal.ROUND_HALF_UP)
Decimal('0.01')
```

**Comment by tbm** [comment]
interesting... I just ran the example through beancount and I also get 4.78 there (same behaviour as ledger), not the 4.79 I was expecting.

**Comment by tbm** [comment]
Same with hledger.

**Comment by tbm** [comment]
note that #1765 has some good test cases as well.

**Comment by simonmichael** [comment]
hledger does banker's rounding, AKA https://en.wikipedia.org/wiki/Rounding#Round_half_to_even .
(only the latest version guarantees this; in earlier versions it depends on the version of Decimal built with.)

**Comment by tbm** [comment]
> roundto gives the behavior you expected:
>
> ledger eval 'roundto(3 * 1.595, 2)'
> >>> 4.79

But minus the same value gives -4.78, which seems bad because things won't balance.

```
ledger eval 'roundto(3 * -1.595, 2)'
-4.78
```

**Comment by tbm** [comment]
> hledger does banker's rounding, AKA https://en.wikipedia.org/wiki/Rounding#Round_half_to_even .
> (only the latest version guarantees this; in earlier versions it depends on the version of Decimal built with.)

When I originally read this, I thought this makes sense but now that I look at it again I don't think it does.  I'm surprised this is what's "banker's rounding" because I don't think this is what banks do.

I think the right rounding is what Python's [decimal](https://docs.python.org/3/library/decimal.html) calls:
 
> decimal.ROUND_HALF_UP
>
>   Round to nearest with ties going away from zero.

Or possibly decimal.ROUND_05UP. I'm not sure how that's different to ROUND_HALF_UP.

**Comment by the-solipsist** [comment]
Even through "rounding half up" is what is most commonly taught in school, I don't feel it is necessary or correct for the functioning of ledger, depending on what "up" means.  (Does "up" mean "towards +∞" or "away from 0"?)

The main requirement from a rounding function for accounting is symmetry of treatment between positive and negative numbers.  Thus, an appropriate rounding function would not display a positive/negative bias.

This means that two of Python's decimal's rounding methods are out.  ROUND_CEILING, and ROUND_FLOOR can't be considered since they use +∞ or -∞ as the limiting value.  All of the remaining 6 use 0 as the limiting value.  Using 0 as the limiting value ensures freedom from positive/negative bias, and symmetrical functioning of the rounding function with respect to positive and negative numbers.

Out of the remaining 6, 3 are not really practical: ROUND_05UP (for reasons explained below), ROUND_DOWN, and ROUND_UP.  ROUND_DOWN will round 10.9 to 10, and ROUND_UP will round 10.1 to 11.  This is not desirable.  Now only three remain: ROUND_HALF_UP, ROUND_HALF_DOWN, and ROUND_HALF_EVEN.  

Any of those 3 would be fine, but out of those, ROUND_HALF_EVEN is the only one that is also free from toward/away from zero bias, which the other 2 exhibit, and thus reduces the error from drift across multiple rounding operations.

That reduction in error across repeated rounding operations is why ROUND_HALF_EVEN is the default rounding method under Python's decimal, under IEEE 754 ("roundTiesToEven"), as well as for MPFR (MPFR_RNDN).

While I think it is fine to use ROUND_HALF_UP (since in Python's decimal, that's equivalent to what Wikipedia calls "Round half away from zero" rather than what Wikipedia calls "Round half up"), I think it is just as well to use ROUND_HALF_EVEN ("banker's rounding").

Importantly, rounding functions should be applied as late as possible to minimize rounding errors.

> Or possibly decimal.ROUND_05UP. I'm not sure how that's different to ROUND_HALF_UP.

ROUND_05UP works like ROUND_DOWN (round towards zero) normally, but acts like ROUND_UP IFF the last digit after rounding is 0 or 5.  Thus it tries to *avoid* ending up at the numbers 0 and 5, preferring 9 and 1 over 0, and 4 and 6 over 5.  So, with a precision of 3 and ROUND_05UP, 10.0 + 0.41 = 10.4, but 10.0 + 0.51 = 10.6, and 10.0 + 0.01 = 10.1.  I've summarized the results in a table for easier understanding.


Sum | 05UP | UP | DOWN | HALF_UP | HALF_EVEN
------ | ----------- | --- | ---- | --- | --- | 
10.0 + 0.41 | 10.4 | 10.5 | 10.4 | 10.4 | 10.4 
10.0 + 0.51 | 10.6 | 10.6 | 10.5 | 10.5 | 10.5
10.0 + 0.01 | 10.1 | 10.1 | 10.0 | 10.0 | 10.0

**Comment by maxnikulin** [comment]
Why floating point arithmetic is required to represent a number as a string? A part of `amount_t::in_place_roundto(int)` implementation proposed in #2361 should be enough to get rounded value. The question is whether a half should always be rounded away from zero. With rounding to even accumulated error may be a bit smaller. Anyway it can be easily adjusted by changing condition when 1 is added to division result.

I am surprised that another case of rounding, namely `amount_t::in_place_truncate()` is implemented using conversion to string and back. I would expect just `in_place_roundto(display_precision())`.

**Comment by maxnikulin** [comment]
Pull requests related to `amount_t::in_place_roundto` have been merged, now halves are consistently rounded to nearest even: `roundto(4.785) == 4.78` and `roundto(-4.785) == -4.78`; and `in_place_truncate` is implemented using `in_place_roundto`. I do not think great efforts are required to change it to `roundto(4.785) == 4.79` and `roundto(-4.785) == -4.79` (round halves away from zero).

The question is whether there are people who would be unhappy due to the change. Perhaps they just keep silence. However since rounding behavior was strange enough, they need some workarounds.

Some cases related to rounding are collected in https://github.com/ledger/ledger/pull/2361#issuecomment-2238867022 Those who wish to see 0.005 rounded up may review them to figure out if it may cause undesired effect.

**Comment by jwiegley** [comment]
If anyone is still unhappy with the way rounding results are produced, a new ticket should be added. I am closing this one as now resolved.
