### ISSUE TITLE
acprep prefix not recognized?

### ISSUE THREAD

**Issue by knowhy** [ledger/ledger#1885]
I was able to compile ledger on my ArchLinux system. After installing ledger via `make install` the ledger command fails with:

```
[me@laptop ~]$ ledger 
ledger: error while loading shared libraries: libledger.so.3: cannot open shared object file: No such file or directory
```

Coping the `libledger.so*` files from `/usr/local/lib/` to `/usr/lib/` resolves the problem.

I compiled ledger with `./acprep update --prefix=/usr/local ` but it seems that ledger looks for `libledger.so` under `/usr/lib` despite `make install` copied it to `/usr/local/lib/`.

**Comment by nobodyinperson** [comment]
Seems to ignore `--prefix` altogether.

**Comment by tbm** [comment]
@q3aiml ;)

**Comment by q3aiml** [comment]
Might be due to removal of `CMAKE_INSTALL_RPATH` in https://github.com/ledger/ledger/commit/6d4cd58cd4b1b2f3906889009da7b71931645e93#diff-95e351a3805a1dafa85bf20b81d086e6L275.

@knowhy @nobodyinperson @tbm can one of you try adding it back and seeing if it fixes it.

@xnox do you remember why the rpath setting was removed?

**Comment by tbm** [comment]
@xnox any comment on this?

**Comment by tbm** [comment]
@nobodyinperson @knowhy can you test the change @q3aiml proposed?

@xnox can you comment on this?

**Comment by knowhy** [comment]
Thanks, I believe that resolves the issue. I have opened a PR here: https://github.com/ledger/ledger/pull/1896
