### ISSUE TITLE
Single quotation marks rendered incorrectly in PDF

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1898]
The manual defines things like:

```
@itemx expr has_tag('TAG')
```

In the HTML manual this is displayed correctly:

```
expr has_tag('TAG')
```

But in the PDF the single quotation marks (even in commands) become UTF-8 quotation marks which are not valid:

```
expr has_tag(’TAG’)
```

Any idea how to fix this?

@enderw88

**Comment by kayb01000010** [comment]
[This](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Inserting-Quote-Characters.html) (links to GNU docs) might be of help.

TeX uses ' for U+0027(apostrophe) and also for U+2019(right single quote)
U+2019 is being rendered in the pdf instead of U+0027

P.S. I'm not an expert. This is only my deduction 😅.

**Comment by tbm** [comment]
> P.S. I'm not an expert. This is only my deduction

Thank you. This works!
