### ISSUE TITLE
roundto() rounding issue: negative and positive not the same

### ISSUE THREAD

**Issue by tbm** [ledger/ledger#1983]
```
ledger eval 'roundto(10 * 0.0775, 2)'
0.78
ledger eval 'roundto(-10 * 0.0775, 2)'
-0.77
```

You get 0.78 and -0.77, which means that certain transactions won't balance.

Here's a test case:

```
= /^Expenses:Pizza$/
    Expenses:Pizza:Taxes           (roundto(amount * 0.0775, 2))
    Liabilities:CreditCard        (roundto(-amount * 0.0775, 2))

2020-12-29 * Test
    Expenses:Pizza                   10.00 USD
    Liabilities:CreditCard          -10.00 USD
```

gives:

```
Unbalanced remainder is:
            0.01 USD
Amount to balance against:
           10.78 USD
While applying automated transaction ...
```

Note that this issue is different to the rounding issue in #1663

**Comment by the-solipsist** [comment]
This bug arises because `roundto` uses the function `ceil()`: https://github.com/ledger/ledger/blob/next/src/amount.cc#L685

The `ceil()` function rounds up towards +∞, as seen in [the examples on this page](https://www.geeksforgeeks.org/ceil-floor-functions-cpp/).  For financial accounting, one should use a rounding function rounds up/down away from 0, as I explained in a [comment to another issue](https://github.com/ledger/ledger/issues/1663#issuecomment-752182284).

**Comment by the-solipsist** [comment]
If `ceil()` is used internally for purposes other than providing the `roundto()` function for users, then that should be fixed.

However, insofar as `roundto()` is concerned, an easy workaround (as pointed out [on the mailing list](https://groups.google.com/g/ledger-cli/c/f47jLxyLwyQ/m/x4xSF8oEBgAJ)), is to place to the minus sign outside of the `roundto()` function.

```
ledger eval 'roundto(10 * 0.0775, 2)'
0.78
ledger eval '(-roundto(-10 * 0.0775, 2))'
-0.78
```

If it isn't worth replacing the `ceil()` function, then this behaviour should be documented in the manual.

**Comment by maxnikulin** [comment]
To my surprise there is a unit test that fails if `roundto` behavior in respect to sign inversion is fixed:
https://github.com/ledger/ledger/commit/185656e191#diff-13332abb7fc3cbdcab10016305ee16e23a7be2ac9229d6b29b6ff633e530d9acR8231-R8237
```
Assets:Cash ¤ -123,40
Expenses:Office Supplies ¤ 123,50
```
Input is
```
; ledger -f - --format "%(account) %(roundto(amount, 1))\n" reg
2015/01/16 * (C0D3) Payee
  Assets:Cash                 ¤ -123,45
    ; Payee: PiggyBank
  Expenses:Office Supplies
```
I hope, 4 vs 5 difference is not intentional and the purpose is that just single digit after decimal separator is not zero.

See pull request #2361 for an attempt to fix `roundto()`.
