### ISSUE TITLE
How to specify multiple files in LEDGER_FILE environment variable?

### ISSUE THREAD

**Issue by aramirezverbio** [ledger/ledger#1997]
I am running ledger 3.2.1-20200518 on an up-to-date Arch Linux on x86_64. I installed it from the official Arch repos.

I can specify multiple ledgers in the command line by adding them with `-f` like `-f file1 -f file2`, but how could I achieve the same effect using the `LEDGER_FILE` environment variable? [This site](https://linux.die.net/man/1/ledger) shows a ledger manpage saying:
> FILE may also be a list of file names separated by colons.

But this is not in my manpage, nor in the manpage in this repo. I tested it anyways and the colon-separated list is not recognised by either the `-f` argument nor the `LEDGER_FILE` variable. Is there any way to achieve this functionality?

**Comment by kanreki** [comment]
The way I deal with it is to have one small main file, consisting of nothing but a few "include" lines. You could think of it as a manifest, or table of contents:

```
$ cat toc
include file1
include file2
$ export LEDGER_FILE=toc
$
```

**Comment by Anachron** [comment]
Yes, I think the correct way to handle this is as @kanreki has pointed out using includes.

**Comment by afh** [comment]
Closing this issue because

* Use of environment variables to specify input files is commented as deprecated, see [`src/global.cc:397`](https://github.com/ledger/ledger/blob/master/src/global.cc#L397)
* Another input file with several `include` statements can be specified (as [mentioned above](https://github.com/ledger/ledger/issues/1997#issuecomment-773554552))
