### ISSUE TITLE
Unable to run python with `ledger` binding support

### ISSUE THREAD

**Issue by char16t** [ledger/ledger#2038]
**Problem:**

Unable to run python with `ledger` binding support. I want to run python script:

```python
import ledger
# ...
```

**Actual result:**

```bash
$ ledger python script.py
Error: No journal file was specified (please use -f)
$  ledger -f data.ledger python script.py
Error: Unrecognized command 'python'
```

```bash
$ ledger python -- --version
Error: No journal file was specified (please use -f)
$  ledger -f data.ledger python -- --version
Error: Unrecognized command 'python'
```

**Expected result:**
```
$ ledger python -- --version
Python 2.7.xx
```

```
$ ledger python script.py
some output
```

**Environment:**

OS: Ubuntu 20.04
```
$ uname -a
Linux laptop 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

Ledger 3.2.1
```
$ ledger --version
Ledger 3.2.1-20200518, the command-line accounting tool

Copyright (c) 2003-2019, John Wiegley.  All rights reserved.

This program is made available under the terms of the BSD Public License.
See LICENSE file included with the distribution for details and disclaimer.
```

Ledger has been built from source code (commit 460a5661ac20789aa578dc9fb20f3a1ed47e5699) via:
```
$ git clone git://github.com/ledger/ledger.git
$ cd ledger
$ ./acprep dependecies
$ ./acprep --python update
```

Python:
```
$ python --version
Python 2.7.18
```

**Comment by nagakiran** [comment]
Am also facing this issue. Please update if anyone get it working on ubuntu 20.04

**Comment by tbm** [comment]
@claytonrcarter does the patch from @nagakiran work for you?

Well, if you're using Homebrew, I think you need to report it to them. Maybe they don't enable Python support

**Comment by tbm** [comment]
@q3aiml @xnox can you review this patch?

**Comment by char16t** [comment]
@tbm Unfortunately, this patch did not fix the problem. Moreover, I checked for `python2.7` and `python` executables in my system and they should be called successfully

**Comment by claytonrcarter** [comment]
Thank you @tbm, but no that patch did not work for me. (Though I'm quite new to ledger and I'm not a python or C dev, so perhaps I didn't build it correctly.) I'll keep an eye on this discussion and report the issue to Homebrew once there's a little more clarify here on what's causing the issue.

**Comment by claytonrcarter** [comment]
No, it does not; at least not for the `brew` installed version on macOS 12.3. Looking more closely, though, the homebrew version seems to lack Python support: `ledger --version` clearly says `without Python support`:

```
❯ ledger --version
Ledger 3.3.2-20230330, the command-line accounting tool
with support for gpg encrypted journals and without Python support

Copyright (c) 2003-2023, John Wiegley.  All rights reserved.

This program is made available under the terms of the BSD Public License.
See LICENSE file included with the distribution for details and disclaimer.

❯ ledger python -- --version
Error: No journal file was specified (please use -f)

❯ ledger python -f ../accounting/current.ledger -- --version
Error: Unrecognized command 'python'
```

I tried `brew reinstall ledger --build-from-source` which seemed to succeed, but still reported `without Python support`.

I'm trying to build directly from `master` but running into some dependency issues. If I get those sorted out, I'll report back.

**Comment by claytonrcarter** [comment]
I wouldn't trust me on this. 😄 I got my build working, but it to reports `without Python support` ... so it might just be something about my machine that is blocking my python support.

**Comment by afh** [comment]
As I'm a bit confused about the error messages from ledger, i.e. Why does `ledger python -- -version` ask for a journal file, when `ledger python` is intented to drop you into the Python REPL? So would you mind adding `--args-only` as to ensure that all arguments are passed on the command-line rather than also taken from any `.ledgerrc`'s you may have in your XDG_CONFIG_HOME, home, or current directory.

That said, the [ledger homebrew formula info page](https://formulae.brew.sh/formula/ledger#default) mentions installations with the `--with-boost-python3` option, but I don't see that anywhere in the actual [`formula.rb`](https://github.com/Homebrew/homebrew-core/blob/d3f0c1bcdc481b5bd6f28db6df3336368837a7cb/Formula/ledger.rb).

In order to build ledger with support for Python pass `--python` to `acprep` or specify the `-DUSE_PYTHON:BOOL=ON` option when invoking the `cmake` command. I see neither in the homebrew formula in [`args`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ledger.rb#L42).

I may have failed to understand how to use homebrew's boost and boost-python3 split formulae properly, but it broke building ledger for me when it was introduced and I thought it to be in violation of good package maintainer practice. Eventually that drove me away from Homebrew and towards nixpkgs and I must say I'm rather thankful. Admittedly nixpkgs is rather annoying to get set up, yet once it does it provides for a much more isolated and independent setup allowing be to rollback when things break.

**Comment by claytonrcarter** [comment]
> Why does ledger python -- -version ask for a journal file, when ledger python is intented to drop you into the Python REPL?

Totally speculating, but is the `python` subcommand only available when built Python support is built in? Here's some sample output with `--args-only` (note that `ledger python` behaves the same as `ledger foobar`)

```
❯ ./ledger python -- --version
Error: No journal file was specified (please use -f)

❯ ./ledger --args-only python -- --version
Error: No journal file was specified (please use -f)

❯ ./ledger --args-only python -f ~/src/accounting/current.ledger -- --version
Error: Unrecognized command 'python'

❯ ./ledger --args-only foobar -- --version
Error: No journal file was specified (please use -f)

❯ ./ledger --args-only foobar -f ~/src/accounting/current.ledger -- --version
Error: Unrecognized command 'foobar'
```

> mentions installations with the --with-boost-python3 option

Could that be an old version? I just tried `brew install ledger --build-from-source --with-boost-python3` and it gave me `Error: invalid option: --with-boost-python3` and trying `brew info ledger` only shows `--HEAD` as an option.

> In order to build ledger with support for Python pass --python to acprep or specify the -DUSE_PYTHON:BOOL=ON option when invoking the cmake command.

Hmm. I tried `./acprep update --python -j 4` last night and that didn't work (as I reported above), but I just did `./acprep gitclean` and then tried `./acprep update --python -j 4` again and that *did* work:

```
❯ ./acprep gitclean
acprep: INFO: Invoking primary phase: gitclean
acprep: INFO: Executing phase: gitclean
Removing CMakeCache.txt
... snip

❯ ./acprep --python -j 4
acprep: INFO: Invoking primary phase: config
... snip (but snipped output does mention finding Python 3.11)

❯ ./acprep update --python -j 4
acprep: INFO: Invoking primary phase: update
... snip (and snipped output again mentions finding Python 3.11)

❯ ./ledger --version
Ledger 3.3.2-20230330, the command-line accounting tool
without support for gpg encrypted journals and with Python support

Copyright (c) 2003-2023, John Wiegley.  All rights reserved.

This program is made available under the terms of the BSD Public License.
See LICENSE file included with the distribution for details and disclaimer.

❯ ./ledger --args-only python -- --version
Python 3.11.3

❯ ./ledger python python/demo.py
Welcome to the Ledger.Python demo!
Demo completed successfully.
```

So, I think that's a win!?

> drove me away from Homebrew and towards nixpkgs and I must say I'm rather thankful

This may be the comment that gets me to try `nix`. Homebrew has been great, but the "always use the latest version" has caused more headaches than I care to admit over the years. Being able to upgrade on my schedule would be great. Thanks for the tip!

**Comment by afh** [comment]
> Totally speculating, but is the python subcommand only available when built Python support is built in? 

Yes, that's totally. I had expected that ledger would err out with "unknown" command, but possibly ledger parses all option prior to parsing the commands…

> Could that be an old version? 

Yes, the `--with-boost-python3` could be an old option, that has since been deleted. I've been off homebrew and on nixpkgs for a few years now.

> So, I think that's a win!?

Very much so!! If you have questions regarding Ledger's Python API please ask. I've been using it quite extensively the past years and am always happy to learn from new users and share my experience.

> This may be the comment that gets me to try nix.

Also happy to answer some questions and share my experience. It's no silver bullet, yet for me the tradeoff has been very much worthwhile, YMMV :)

**Comment by char16t** [comment]
It worked for me! Thank you @afh, @claytonrcarter

**Comment by afh** [comment]
Thanks for reporting back and closing out this issue, @char16t! Glad to hear that you got Ledger with support for Python working. Happy hacking!!

The documentation around the Python module is lacking, if you have suggestions, ideas, questions, please reach out.
And while the following currently only provides the raw API without any comments it might be better than nothing: `python -m pydoc -w ledger` will write out documentation for the Ledger Python module to `ledger.html` (be sure that python is setup to be able to load the ledger module, e.g. by setting `PYTHONPATH=${PATH_TO_DIRECTORY_WITH_ledger.so}`
