### ISSUE TITLE
Compilation messages with latest boost

### ISSUE THREAD

**Issue by mkschreder** [ledger/ledger#2227]
Lots of new messages like this coming up:

```
In file included from /usr/include/boost/bind.hpp:30,
                 from /ledger-3.3.2/build/system.hh:139,
                 from /ledger-3.3.2/src/ptree.cc:32:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
```

**Comment by tbm** [comment]
Is this an error or a warning?  I assume a warning since you changed the title.

Which version of boost?

**Comment by afh** [comment]
Thanks for reporting, @mkschreder.

What you are seeing might be related to https://github.com/boostorg/python/issues/359. Checking Ledger's source there are a few uses of `_1` and `_2`:

```
grep -cR ' _[12]' src | grep '[^0]$'
src/op.h:1
src/account.h:2
src/py_commodity.cc:4
src/option.h:2
src/filters.h:1
```

When I build ledger using the [Ledger flake.nix](https://github.com/ledger/ledger/blob/master/flake.nix) and change it to use Boost 1.81 I do not see any compilation warnings. Until I've figured out how to make the build more verbose it would be helpful to learn more details about how you build ledger specifically, so that I could try and reproduce that on my machine.

**Comment by afh** [comment]
@mkschreder mind trying out the patch below to see if that removes the messages?

Unfortunately I'm currently unable to build Ledger with boost <1.75 to verify that the patch maintains backwards compatibility.

[boost-bind.patch](https://github.com/ledger/ledger/files/11190732/boost-bind.patch)

To apply the patch the following command can be run from within the ledger workspace directory:
`% curl -sL https://github.com/ledger/ledger/files/11190732/boost-bind.patch | patch -p1`

**Comment by afh** [comment]
Friendly ping for @mkschreder on this :)
